// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MovieSearchClient is the client API for MovieSearch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MovieSearchClient interface {
	SearchMovie(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type movieSearchClient struct {
	cc grpc.ClientConnInterface
}

func NewMovieSearchClient(cc grpc.ClientConnInterface) MovieSearchClient {
	return &movieSearchClient{cc}
}

func (c *movieSearchClient) SearchMovie(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/MovieSearch/SearchMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovieSearchServer is the server API for MovieSearch service.
// All implementations must embed UnimplementedMovieSearchServer
// for forward compatibility
type MovieSearchServer interface {
	SearchMovie(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedMovieSearchServer()
}

// UnimplementedMovieSearchServer must be embedded to have forward compatible implementations.
type UnimplementedMovieSearchServer struct {
}

func (UnimplementedMovieSearchServer) SearchMovie(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchMovie not implemented")
}
func (UnimplementedMovieSearchServer) mustEmbedUnimplementedMovieSearchServer() {}

// UnsafeMovieSearchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MovieSearchServer will
// result in compilation errors.
type UnsafeMovieSearchServer interface {
	mustEmbedUnimplementedMovieSearchServer()
}

func RegisterMovieSearchServer(s grpc.ServiceRegistrar, srv MovieSearchServer) {
	s.RegisterService(&MovieSearch_ServiceDesc, srv)
}

func _MovieSearch_SearchMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieSearchServer).SearchMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MovieSearch/SearchMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieSearchServer).SearchMovie(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MovieSearch_ServiceDesc is the grpc.ServiceDesc for MovieSearch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MovieSearch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MovieSearch",
	HandlerType: (*MovieSearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchMovie",
			Handler:    _MovieSearch_SearchMovie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "movie.proto",
}
